/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ConteudosRouteImport } from './routes/conteudos'
import { Route as CotacaoRouteImport } from './routes/cotacao'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SolucoesRouteImport } from './routes/solucoes'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as AdminProtectedRouteImport } from './routes/admin/_protected'
import { Route as AdminAcessoNegadoRouteImport } from './routes/admin/acesso-negado'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ProdutosIndexRouteImport } from './routes/produtos/index'
import { Route as AdminProtectedIndexRouteImport } from './routes/admin/_protected/index'
import { Route as AdminProtectedAuditoriaRouteImport } from './routes/admin/_protected/auditoria'
import { Route as AdminProtectedConflitosRouteImport } from './routes/admin/_protected/conflitos'
import { Route as AdminProtectedImportacaoRouteImport } from './routes/admin/_protected/importacao'
import { Route as AdminProtectedMidiaRouteImport } from './routes/admin/_protected/midia'
import { Route as AdminProtectedNormalizacaoRouteImport } from './routes/admin/_protected/normalizacao'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicOutboxWorkerRouteImport } from './routes/api/public/outbox-worker'
import { Route as ProdutosCategorySlugIndexRouteImport } from './routes/produtos/$categorySlug/index'
import { Route as ProdutosCategorySlugFamilySlugRouteImport } from './routes/produtos/$categorySlug/$familySlug'
import { Route as AdminProtectedCatalogoFamiliasRouteImport } from './routes/admin/_protected/catalogo/familias'
import { Route as AdminProtectedCatalogoSkusRouteImport } from './routes/admin/_protected/catalogo/skus'
import { Route as AdminProtectedCatalogoTaxonomiaRouteImport } from './routes/admin/_protected/catalogo/taxonomia'
import { Route as AdminProtectedImportacaoJobIdRouteImport } from './routes/admin/_protected/importacao_.$jobId'
import { Route as AdminProtectedCatalogoFamiliasFamilyIdRouteImport } from './routes/admin/_protected/catalogo/familias_.$familyId'
import { Route as AdminProtectedCatalogoSkusProductIdRouteImport } from './routes/admin/_protected/catalogo/skus_.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosRoute = ConteudosRouteImport.update({
  id: '/conteudos',
  path: '/conteudos',
  getParentRoute: () => rootRouteImport,
} as any)
const CotacaoRoute = CotacaoRouteImport.update({
  id: '/cotacao',
  path: '/cotacao',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesRoute = SolucoesRouteImport.update({
  id: '/solucoes',
  path: '/solucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProtectedRoute = AdminProtectedRouteImport.update({
  id: '/admin/_protected',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAcessoNegadoRoute = AdminAcessoNegadoRouteImport.update({
  id: '/admin/acesso-negado',
  path: '/admin/acesso-negado',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosIndexRoute = ProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProtectedIndexRoute = AdminProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const AdminProtectedAuditoriaRoute = AdminProtectedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const AdminProtectedConflitosRoute = AdminProtectedConflitosRouteImport.update({
  id: '/conflitos',
  path: '/conflitos',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const AdminProtectedImportacaoRoute =
  AdminProtectedImportacaoRouteImport.update({
    id: '/importacao',
    path: '/importacao',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedMidiaRoute = AdminProtectedMidiaRouteImport.update({
  id: '/midia',
  path: '/midia',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const AdminProtectedNormalizacaoRoute =
  AdminProtectedNormalizacaoRouteImport.update({
    id: '/normalizacao',
    path: '/normalizacao',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOutboxWorkerRoute = ApiPublicOutboxWorkerRouteImport.update({
  id: '/api/public/outbox-worker',
  path: '/api/public/outbox-worker',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosCategorySlugIndexRoute =
  ProdutosCategorySlugIndexRouteImport.update({
    id: '/produtos/$categorySlug/',
    path: '/produtos/$categorySlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProdutosCategorySlugFamilySlugRoute =
  ProdutosCategorySlugFamilySlugRouteImport.update({
    id: '/produtos/$categorySlug/$familySlug',
    path: '/produtos/$categorySlug/$familySlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminProtectedCatalogoFamiliasRoute =
  AdminProtectedCatalogoFamiliasRouteImport.update({
    id: '/catalogo/familias',
    path: '/catalogo/familias',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedCatalogoSkusRoute =
  AdminProtectedCatalogoSkusRouteImport.update({
    id: '/catalogo/skus',
    path: '/catalogo/skus',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedCatalogoTaxonomiaRoute =
  AdminProtectedCatalogoTaxonomiaRouteImport.update({
    id: '/catalogo/taxonomia',
    path: '/catalogo/taxonomia',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedImportacaoJobIdRoute =
  AdminProtectedImportacaoJobIdRouteImport.update({
    id: '/importacao_/$jobId',
    path: '/importacao/$jobId',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedCatalogoFamiliasFamilyIdRoute =
  AdminProtectedCatalogoFamiliasFamilyIdRouteImport.update({
    id: '/catalogo/familias_/$familyId',
    path: '/catalogo/familias/$familyId',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedCatalogoSkusProductIdRoute =
  AdminProtectedCatalogoSkusProductIdRouteImport.update({
    id: '/catalogo/skus_/$productId',
    path: '/catalogo/skus/$productId',
    getParentRoute: () => AdminProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/contato': typeof ContatoRoute
  '/conteudos': typeof ConteudosRoute
  '/cotacao': typeof CotacaoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/solucoes': typeof SolucoesRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin': typeof AdminProtectedRouteWithChildren
  '/admin/acesso-negado': typeof AdminAcessoNegadoRoute
  '/admin/login': typeof AdminLoginRoute
  '/produtos/': typeof ProdutosIndexRoute
  '/admin/auditoria': typeof AdminProtectedAuditoriaRoute
  '/admin/conflitos': typeof AdminProtectedConflitosRoute
  '/admin/importacao': typeof AdminProtectedImportacaoRoute
  '/admin/midia': typeof AdminProtectedMidiaRoute
  '/admin/normalizacao': typeof AdminProtectedNormalizacaoRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/outbox-worker': typeof ApiPublicOutboxWorkerRoute
  '/produtos/$categorySlug/$familySlug': typeof ProdutosCategorySlugFamilySlugRoute
  '/admin/': typeof AdminProtectedIndexRoute
  '/produtos/$categorySlug/': typeof ProdutosCategorySlugIndexRoute
  '/admin/catalogo/familias': typeof AdminProtectedCatalogoFamiliasRoute
  '/admin/catalogo/skus': typeof AdminProtectedCatalogoSkusRoute
  '/admin/catalogo/taxonomia': typeof AdminProtectedCatalogoTaxonomiaRoute
  '/admin/importacao/$jobId': typeof AdminProtectedImportacaoJobIdRoute
  '/admin/catalogo/familias/$familyId': typeof AdminProtectedCatalogoFamiliasFamilyIdRoute
  '/admin/catalogo/skus/$productId': typeof AdminProtectedCatalogoSkusProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/contato': typeof ContatoRoute
  '/conteudos': typeof ConteudosRoute
  '/cotacao': typeof CotacaoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/solucoes': typeof SolucoesRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/acesso-negado': typeof AdminAcessoNegadoRoute
  '/admin/login': typeof AdminLoginRoute
  '/produtos': typeof ProdutosIndexRoute
  '/admin/auditoria': typeof AdminProtectedAuditoriaRoute
  '/admin/conflitos': typeof AdminProtectedConflitosRoute
  '/admin/importacao': typeof AdminProtectedImportacaoRoute
  '/admin/midia': typeof AdminProtectedMidiaRoute
  '/admin/normalizacao': typeof AdminProtectedNormalizacaoRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/outbox-worker': typeof ApiPublicOutboxWorkerRoute
  '/produtos/$categorySlug/$familySlug': typeof ProdutosCategorySlugFamilySlugRoute
  '/admin': typeof AdminProtectedIndexRoute
  '/produtos/$categorySlug': typeof ProdutosCategorySlugIndexRoute
  '/admin/catalogo/familias': typeof AdminProtectedCatalogoFamiliasRoute
  '/admin/catalogo/skus': typeof AdminProtectedCatalogoSkusRoute
  '/admin/catalogo/taxonomia': typeof AdminProtectedCatalogoTaxonomiaRoute
  '/admin/importacao/$jobId': typeof AdminProtectedImportacaoJobIdRoute
  '/admin/catalogo/familias/$familyId': typeof AdminProtectedCatalogoFamiliasFamilyIdRoute
  '/admin/catalogo/skus/$productId': typeof AdminProtectedCatalogoSkusProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/contato': typeof ContatoRoute
  '/conteudos': typeof ConteudosRoute
  '/cotacao': typeof CotacaoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/solucoes': typeof SolucoesRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/_protected': typeof AdminProtectedRouteWithChildren
  '/admin/acesso-negado': typeof AdminAcessoNegadoRoute
  '/admin/login': typeof AdminLoginRoute
  '/produtos/': typeof ProdutosIndexRoute
  '/admin/_protected/auditoria': typeof AdminProtectedAuditoriaRoute
  '/admin/_protected/conflitos': typeof AdminProtectedConflitosRoute
  '/admin/_protected/importacao': typeof AdminProtectedImportacaoRoute
  '/admin/_protected/midia': typeof AdminProtectedMidiaRoute
  '/admin/_protected/normalizacao': typeof AdminProtectedNormalizacaoRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/outbox-worker': typeof ApiPublicOutboxWorkerRoute
  '/produtos/$categorySlug/$familySlug': typeof ProdutosCategorySlugFamilySlugRoute
  '/admin/_protected/': typeof AdminProtectedIndexRoute
  '/produtos/$categorySlug/': typeof ProdutosCategorySlugIndexRoute
  '/admin/_protected/catalogo/familias': typeof AdminProtectedCatalogoFamiliasRoute
  '/admin/_protected/catalogo/skus': typeof AdminProtectedCatalogoSkusRoute
  '/admin/_protected/catalogo/taxonomia': typeof AdminProtectedCatalogoTaxonomiaRoute
  '/admin/_protected/importacao_/$jobId': typeof AdminProtectedImportacaoJobIdRoute
  '/admin/_protected/catalogo/familias_/$familyId': typeof AdminProtectedCatalogoFamiliasFamilyIdRoute
  '/admin/_protected/catalogo/skus_/$productId': typeof AdminProtectedCatalogoSkusProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/busca'
    | '/contato'
    | '/conteudos'
    | '/cotacao'
    | '/politica-de-privacidade'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sobre'
    | '/solucoes'
    | '/termos-de-uso'
    | '/admin'
    | '/admin/acesso-negado'
    | '/admin/login'
    | '/produtos/'
    | '/admin/auditoria'
    | '/admin/conflitos'
    | '/admin/importacao'
    | '/admin/midia'
    | '/admin/normalizacao'
    | '/api/public/health'
    | '/api/public/outbox-worker'
    | '/produtos/$categorySlug/$familySlug'
    | '/admin/'
    | '/produtos/$categorySlug/'
    | '/admin/catalogo/familias'
    | '/admin/catalogo/skus'
    | '/admin/catalogo/taxonomia'
    | '/admin/importacao/$jobId'
    | '/admin/catalogo/familias/$familyId'
    | '/admin/catalogo/skus/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/busca'
    | '/contato'
    | '/conteudos'
    | '/cotacao'
    | '/politica-de-privacidade'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sobre'
    | '/solucoes'
    | '/termos-de-uso'
    | '/admin/acesso-negado'
    | '/admin/login'
    | '/produtos'
    | '/admin/auditoria'
    | '/admin/conflitos'
    | '/admin/importacao'
    | '/admin/midia'
    | '/admin/normalizacao'
    | '/api/public/health'
    | '/api/public/outbox-worker'
    | '/produtos/$categorySlug/$familySlug'
    | '/admin'
    | '/produtos/$categorySlug'
    | '/admin/catalogo/familias'
    | '/admin/catalogo/skus'
    | '/admin/catalogo/taxonomia'
    | '/admin/importacao/$jobId'
    | '/admin/catalogo/familias/$familyId'
    | '/admin/catalogo/skus/$productId'
  id:
    | '__root__'
    | '/'
    | '/busca'
    | '/contato'
    | '/conteudos'
    | '/cotacao'
    | '/politica-de-privacidade'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sobre'
    | '/solucoes'
    | '/termos-de-uso'
    | '/admin/_protected'
    | '/admin/acesso-negado'
    | '/admin/login'
    | '/produtos/'
    | '/admin/_protected/auditoria'
    | '/admin/_protected/conflitos'
    | '/admin/_protected/importacao'
    | '/admin/_protected/midia'
    | '/admin/_protected/normalizacao'
    | '/api/public/health'
    | '/api/public/outbox-worker'
    | '/produtos/$categorySlug/$familySlug'
    | '/admin/_protected/'
    | '/produtos/$categorySlug/'
    | '/admin/_protected/catalogo/familias'
    | '/admin/_protected/catalogo/skus'
    | '/admin/_protected/catalogo/taxonomia'
    | '/admin/_protected/importacao_/$jobId'
    | '/admin/_protected/catalogo/familias_/$familyId'
    | '/admin/_protected/catalogo/skus_/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscaRoute: typeof BuscaRoute
  ContatoRoute: typeof ContatoRoute
  ConteudosRoute: typeof ConteudosRoute
  CotacaoRoute: typeof CotacaoRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  SolucoesRoute: typeof SolucoesRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  AdminProtectedRoute: typeof AdminProtectedRouteWithChildren
  AdminAcessoNegadoRoute: typeof AdminAcessoNegadoRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ProdutosIndexRoute: typeof ProdutosIndexRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicOutboxWorkerRoute: typeof ApiPublicOutboxWorkerRoute
  ProdutosCategorySlugFamilySlugRoute: typeof ProdutosCategorySlugFamilySlugRoute
  ProdutosCategorySlugIndexRoute: typeof ProdutosCategorySlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos': {
      id: '/conteudos'
      path: '/conteudos'
      fullPath: '/conteudos'
      preLoaderRoute: typeof ConteudosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotacao': {
      id: '/cotacao'
      path: '/cotacao'
      fullPath: '/cotacao'
      preLoaderRoute: typeof CotacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes': {
      id: '/solucoes'
      path: '/solucoes'
      fullPath: '/solucoes'
      preLoaderRoute: typeof SolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_protected': {
      id: '/admin/_protected'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/acesso-negado': {
      id: '/admin/acesso-negado'
      path: '/admin/acesso-negado'
      fullPath: '/admin/acesso-negado'
      preLoaderRoute: typeof AdminAcessoNegadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/': {
      id: '/produtos/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof ProdutosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_protected/': {
      id: '/admin/_protected/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminProtectedIndexRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/auditoria': {
      id: '/admin/_protected/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminProtectedAuditoriaRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/conflitos': {
      id: '/admin/_protected/conflitos'
      path: '/conflitos'
      fullPath: '/admin/conflitos'
      preLoaderRoute: typeof AdminProtectedConflitosRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/importacao': {
      id: '/admin/_protected/importacao'
      path: '/importacao'
      fullPath: '/admin/importacao'
      preLoaderRoute: typeof AdminProtectedImportacaoRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/midia': {
      id: '/admin/_protected/midia'
      path: '/midia'
      fullPath: '/admin/midia'
      preLoaderRoute: typeof AdminProtectedMidiaRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/normalizacao': {
      id: '/admin/_protected/normalizacao'
      path: '/normalizacao'
      fullPath: '/admin/normalizacao'
      preLoaderRoute: typeof AdminProtectedNormalizacaoRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/outbox-worker': {
      id: '/api/public/outbox-worker'
      path: '/api/public/outbox-worker'
      fullPath: '/api/public/outbox-worker'
      preLoaderRoute: typeof ApiPublicOutboxWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/$categorySlug/': {
      id: '/produtos/$categorySlug/'
      path: '/produtos/$categorySlug'
      fullPath: '/produtos/$categorySlug/'
      preLoaderRoute: typeof ProdutosCategorySlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/$categorySlug/$familySlug': {
      id: '/produtos/$categorySlug/$familySlug'
      path: '/produtos/$categorySlug/$familySlug'
      fullPath: '/produtos/$categorySlug/$familySlug'
      preLoaderRoute: typeof ProdutosCategorySlugFamilySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_protected/catalogo/familias': {
      id: '/admin/_protected/catalogo/familias'
      path: '/catalogo/familias'
      fullPath: '/admin/catalogo/familias'
      preLoaderRoute: typeof AdminProtectedCatalogoFamiliasRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/catalogo/skus': {
      id: '/admin/_protected/catalogo/skus'
      path: '/catalogo/skus'
      fullPath: '/admin/catalogo/skus'
      preLoaderRoute: typeof AdminProtectedCatalogoSkusRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/catalogo/taxonomia': {
      id: '/admin/_protected/catalogo/taxonomia'
      path: '/catalogo/taxonomia'
      fullPath: '/admin/catalogo/taxonomia'
      preLoaderRoute: typeof AdminProtectedCatalogoTaxonomiaRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/importacao_/$jobId': {
      id: '/admin/_protected/importacao_/$jobId'
      path: '/importacao/$jobId'
      fullPath: '/admin/importacao/$jobId'
      preLoaderRoute: typeof AdminProtectedImportacaoJobIdRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/catalogo/familias_/$familyId': {
      id: '/admin/_protected/catalogo/familias_/$familyId'
      path: '/catalogo/familias/$familyId'
      fullPath: '/admin/catalogo/familias/$familyId'
      preLoaderRoute: typeof AdminProtectedCatalogoFamiliasFamilyIdRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/catalogo/skus_/$productId': {
      id: '/admin/_protected/catalogo/skus_/$productId'
      path: '/catalogo/skus/$productId'
      fullPath: '/admin/catalogo/skus/$productId'
      preLoaderRoute: typeof AdminProtectedCatalogoSkusProductIdRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
  }
}

interface AdminProtectedRouteChildren {
  AdminProtectedAuditoriaRoute: typeof AdminProtectedAuditoriaRoute
  AdminProtectedConflitosRoute: typeof AdminProtectedConflitosRoute
  AdminProtectedImportacaoRoute: typeof AdminProtectedImportacaoRoute
  AdminProtectedMidiaRoute: typeof AdminProtectedMidiaRoute
  AdminProtectedNormalizacaoRoute: typeof AdminProtectedNormalizacaoRoute
  AdminProtectedIndexRoute: typeof AdminProtectedIndexRoute
  AdminProtectedCatalogoFamiliasRoute: typeof AdminProtectedCatalogoFamiliasRoute
  AdminProtectedCatalogoSkusRoute: typeof AdminProtectedCatalogoSkusRoute
  AdminProtectedCatalogoTaxonomiaRoute: typeof AdminProtectedCatalogoTaxonomiaRoute
  AdminProtectedImportacaoJobIdRoute: typeof AdminProtectedImportacaoJobIdRoute
  AdminProtectedCatalogoFamiliasFamilyIdRoute: typeof AdminProtectedCatalogoFamiliasFamilyIdRoute
  AdminProtectedCatalogoSkusProductIdRoute: typeof AdminProtectedCatalogoSkusProductIdRoute
}

const AdminProtectedRouteChildren: AdminProtectedRouteChildren = {
  AdminProtectedAuditoriaRoute: AdminProtectedAuditoriaRoute,
  AdminProtectedConflitosRoute: AdminProtectedConflitosRoute,
  AdminProtectedImportacaoRoute: AdminProtectedImportacaoRoute,
  AdminProtectedMidiaRoute: AdminProtectedMidiaRoute,
  AdminProtectedNormalizacaoRoute: AdminProtectedNormalizacaoRoute,
  AdminProtectedIndexRoute: AdminProtectedIndexRoute,
  AdminProtectedCatalogoFamiliasRoute: AdminProtectedCatalogoFamiliasRoute,
  AdminProtectedCatalogoSkusRoute: AdminProtectedCatalogoSkusRoute,
  AdminProtectedCatalogoTaxonomiaRoute: AdminProtectedCatalogoTaxonomiaRoute,
  AdminProtectedImportacaoJobIdRoute: AdminProtectedImportacaoJobIdRoute,
  AdminProtectedCatalogoFamiliasFamilyIdRoute:
    AdminProtectedCatalogoFamiliasFamilyIdRoute,
  AdminProtectedCatalogoSkusProductIdRoute:
    AdminProtectedCatalogoSkusProductIdRoute,
}

const AdminProtectedRouteWithChildren = AdminProtectedRoute._addFileChildren(
  AdminProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscaRoute: BuscaRoute,
  ContatoRoute: ContatoRoute,
  ConteudosRoute: ConteudosRoute,
  CotacaoRoute: CotacaoRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  SolucoesRoute: SolucoesRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  AdminProtectedRoute: AdminProtectedRouteWithChildren,
  AdminAcessoNegadoRoute: AdminAcessoNegadoRoute,
  AdminLoginRoute: AdminLoginRoute,
  ProdutosIndexRoute: ProdutosIndexRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicOutboxWorkerRoute: ApiPublicOutboxWorkerRoute,
  ProdutosCategorySlugFamilySlugRoute: ProdutosCategorySlugFamilySlugRoute,
  ProdutosCategorySlugIndexRoute: ProdutosCategorySlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
