-- Etapa 6.1: semente canonica da taxonomia aprovada e das 31 familias (D-052/D-053).
INSERT INTO public.product_categories (code,name,slug,sort_order,is_active) VALUES
('CAT-01','Vacinação e aplicação','vacinacao-e-aplicacao',1,true),
('CAT-02','Pulverização e sistemas de fluido','pulverizacao-e-sistemas-de-fluido',2,true),
('CAT-03','Pesagem, medição e controle','pesagem-medicao-e-controle',3,true),
('CAT-04','Peças, reposição e automação','pecas-reposicao-e-automacao',4,true),
('CAT-05','Manejo, alimentação e biossegurança','manejo-alimentacao-e-biosseguranca',5,true),
('CAT-06','Linhas complementares','linhas-complementares',6,true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.segments (code,name,slug,sort_order,is_active) VALUES
('SEG-01','Avicultura','avicultura',1,true),
('SEG-02','Bovinocultura','bovinocultura',2,true),
('SEG-03','Suinocultura','suinocultura',3,true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.applications (code,name,slug,sort_order,is_active) VALUES
('APL-01','alimentação','alimentacao',1,true),
('APL-02','aplicação','aplicacao',2,true),
('APL-03','biossegurança','biosseguranca',3,true),
('APL-04','circulação de fluidos','circulacao-de-fluidos',4,true),
('APL-05','controle de pragas','controle-de-pragas',5,true),
('APL-06','controle de temperatura','controle-de-temperatura',6,true),
('APL-07','debicagem','debicagem',7,true),
('APL-08','hidratação','hidratacao',8,true),
('APL-09','incubação','incubacao',9,true),
('APL-10','inspeção','inspecao',10,true),
('APL-11','manejo','manejo',11,true),
('APL-12','manutenção','manutencao',12,true),
('APL-13','medição','medicao',13,true),
('APL-14','monitoramento','monitoramento',14,true),
('APL-15','ovoscopia','ovoscopia',15,true),
('APL-16','pesagem','pesagem',16,true),
('APL-17','pulverização','pulverizacao',17,true),
('APL-18','qualidade da água','qualidade-da-agua',18,true),
('APL-19','qualidade do ambiente','qualidade-do-ambiente',19,true),
('APL-20','reposição','reposicao',20,true),
('APL-21','vacinação','vacinacao',21,true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.solutions (code,name,slug,sort_order,is_active) VALUES
('SOL-01','Linhas complementares','linhas-complementares',1,true),
('SOL-02','Manejo e biossegurança','manejo-e-biosseguranca',2,true),
('SOL-03','Reposição e manutenção','reposicao-e-manutencao',3,true),
('SOL-04','Soluções para pesagem, medição e controle','solucoes-para-pesagem-medicao-e-controle',4,true),
('SOL-05','Soluções para pulverização','solucoes-para-pulverizacao',5,true),
('SOL-06','Soluções para vacinação','solucoes-para-vacinacao',6,true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.product_subcategories (category_id,code,name,slug,is_public,sort_order,is_active)
SELECT c.id, v.code, v.name, v.slug, true, v.ord, true FROM (VALUES
('linhas-complementares','SUB-01','Bovinocultura','linhas-complementares-bovinocultura',1),
('manejo-alimentacao-e-biosseguranca','SUB-02','Bebedouros','manejo-alimentacao-e-biosseguranca-bebedouros',2),
('manejo-alimentacao-e-biosseguranca','SUB-03','Comedouros','manejo-alimentacao-e-biosseguranca-comedouros',3),
('manejo-alimentacao-e-biosseguranca','SUB-04','Consumíveis','manejo-alimentacao-e-biosseguranca-consumiveis',4),
('manejo-alimentacao-e-biosseguranca','SUB-05','Controle de pragas','manejo-alimentacao-e-biosseguranca-controle-de-pragas',5),
('manejo-alimentacao-e-biosseguranca','SUB-06','Manejo','manejo-alimentacao-e-biosseguranca-manejo',6),
('pecas-reposicao-e-automacao','SUB-07','Lâminas','pecas-reposicao-e-automacao-laminas',7),
('pesagem-medicao-e-controle','SUB-08','Balanças de precisão','pesagem-medicao-e-controle-balancas-de-precisao',8),
('pesagem-medicao-e-controle','SUB-09','Balanças para aves','pesagem-medicao-e-controle-balancas-para-aves',9),
('pesagem-medicao-e-controle','SUB-10','Balanças para ovos','pesagem-medicao-e-controle-balancas-para-ovos',10),
('pesagem-medicao-e-controle','SUB-11','Ovoscopia','pesagem-medicao-e-controle-ovoscopia',11),
('pesagem-medicao-e-controle','SUB-12','Qualidade da água','pesagem-medicao-e-controle-qualidade-da-agua',12),
('pesagem-medicao-e-controle','SUB-13','Qualidade do ambiente','pesagem-medicao-e-controle-qualidade-do-ambiente',13),
('pesagem-medicao-e-controle','SUB-14','Termografia','pesagem-medicao-e-controle-termografia',14),
('pesagem-medicao-e-controle','SUB-15','Termômetros','pesagem-medicao-e-controle-termometros',15),
('pulverizacao-e-sistemas-de-fluido','SUB-16','Bicos','pulverizacao-e-sistemas-de-fluido-bicos',16),
('pulverizacao-e-sistemas-de-fluido','SUB-17','Tubulações','pulverizacao-e-sistemas-de-fluido-tubulacoes',17),
('vacinacao-e-aplicacao','SUB-18','Agulhas','vacinacao-e-aplicacao-agulhas',18),
('vacinacao-e-aplicacao','SUB-19','Equipos','vacinacao-e-aplicacao-equipos',19),
('vacinacao-e-aplicacao','SUB-20','Reparo de seringas','vacinacao-e-aplicacao-reparo-de-seringas',20),
('vacinacao-e-aplicacao','SUB-21','Seringas automáticas','vacinacao-e-aplicacao-seringas-automaticas',21),
('vacinacao-e-aplicacao','SUB-22','Seringas descartáveis','vacinacao-e-aplicacao-seringas-descartaveis',22),
('vacinacao-e-aplicacao','SUB-23','Vacinadoras','vacinacao-e-aplicacao-vacinadoras',23)
) AS v(cat_slug,code,name,slug,ord) JOIN public.product_categories c ON c.slug=v.cat_slug ON CONFLICT (code) DO NOTHING;
INSERT INTO public.product_families (reference_code,public_name,admin_name,slug,category_id,subcategory_id,sort_order,review_status,publication_status,source)
SELECT v.ref, v.name, v.name, v.slug, c.id, s.id, v.ord, 'UNDER_REVIEW', 'NOT_PUBLISHED', 'matriz-aprovada:D-052' FROM (VALUES
('FAM-001','Agulhas descartáveis','agulhas-descartaveis','vacinacao-e-aplicacao','Agulhas',1),
('FAM-002','Agulhas inox reutilizáveis','agulhas-inox-reutilizaveis','vacinacao-e-aplicacao','Agulhas',2),
('FAM-004','Agulhas para aplicador de vacina','agulhas-para-aplicador-de-vacina','vacinacao-e-aplicacao','Agulhas',3),
('FAM-005','Seringas automáticas de fluxo contínuo','seringas-automaticas-de-fluxo-continuo','vacinacao-e-aplicacao','Seringas automáticas',4),
('FAM-006','Seringas automáticas duplas','seringas-automaticas-duplas','vacinacao-e-aplicacao','Seringas automáticas',5),
('FAM-007','Vacinadoras com porta-frasco','vacinadoras-com-porta-frasco','vacinacao-e-aplicacao','Vacinadoras',6),
('FAM-008','Kits de reparo para seringas automáticas','kits-de-reparo-para-seringas-automaticas','vacinacao-e-aplicacao','Reparo de seringas',7),
('FAM-009','Seringas descartáveis','seringas-descartaveis','vacinacao-e-aplicacao','Seringas descartáveis',8),
('FAM-013','Equipos para aplicação e infusão','equipos-para-aplicacao-e-infusao','vacinacao-e-aplicacao','Equipos',9),
('FAM-014','Bicos pulverizadores','bicos-pulverizadores','pulverizacao-e-sistemas-de-fluido','Bicos',10),
('FAM-015','Tubulações e mangueiras','tubulacoes-e-mangueiras','pulverizacao-e-sistemas-de-fluido','Tubulações',11),
('FAM-022','Balanças suspensas e dinamômetros para aves','balancas-suspensas-e-dinamometros-para-aves','pesagem-medicao-e-controle','Balanças para aves',12),
('FAM-023','Balanças eletrônicas para aves','balancas-eletronicas-para-aves','pesagem-medicao-e-controle','Balanças para aves',13),
('FAM-024','Balanças para ovos','balancas-para-ovos','pesagem-medicao-e-controle','Balanças para ovos',14),
('FAM-025','Balanças de precisão de bolso','balancas-de-precisao-de-bolso','pesagem-medicao-e-controle','Balanças de precisão',15),
('FAM-026','Termômetros','termometros','pesagem-medicao-e-controle','Termômetros',16),
('FAM-027','Medidores e testes de qualidade da água','medidores-e-testes-de-qualidade-da-agua','pesagem-medicao-e-controle','Qualidade da água',17),
('FAM-028','Testes de qualidade do ambiente','testes-de-qualidade-do-ambiente','pesagem-medicao-e-controle','Qualidade do ambiente',18),
('FAM-029','Equipamentos para ovoscopia','equipamentos-para-ovoscopia','pesagem-medicao-e-controle','Ovoscopia',19),
('FAM-030','Câmeras termográficas','cameras-termograficas','pesagem-medicao-e-controle','Termografia',20),
('FAM-031','Lâminas para debicagem','laminas-para-debicagem','pecas-reposicao-e-automacao','Lâminas',21),
('FAM-033','Bebedouros pendulares para aves','bebedouros-pendulares-para-aves','manejo-alimentacao-e-biosseguranca','Bebedouros',22),
('FAM-034','Comedouros para aves','comedouros-para-aves','manejo-alimentacao-e-biosseguranca','Comedouros',23),
('FAM-035','Niples para bebedouro','niples-para-bebedouro','manejo-alimentacao-e-biosseguranca','Bebedouros',24),
('FAM-036','Armadilhas para roedores','armadilhas-para-roedores','manejo-alimentacao-e-biosseguranca','Controle de pragas',25),
('FAM-037','Adesivos e colas para captura','adesivos-e-colas-para-captura','manejo-alimentacao-e-biosseguranca','Controle de pragas',26),
('FAM-038','Contadores manuais para aves','contadores-manuais-para-aves','manejo-alimentacao-e-biosseguranca','Manejo',27),
('FAM-039','Consumíveis de assepsia e apoio','consumiveis-de-assepsia-e-apoio','manejo-alimentacao-e-biosseguranca','Consumíveis',28),
('FAM-040','Conjunto para aplicação de tuberculina','conjunto-para-aplicacao-de-tuberculina','linhas-complementares','Bovinocultura',29),
('FAM-042','Seringas para insulina','seringas-para-insulina','linhas-complementares','Bovinocultura',30),
('FAM-043','Imãs intra-ruminais','imas-intra-ruminais','linhas-complementares','Bovinocultura',31)
) AS v(ref,name,slug,cat_slug,sub_name,ord) JOIN public.product_categories c ON c.slug=v.cat_slug LEFT JOIN public.product_subcategories s ON s.category_id=c.id AND s.name=v.sub_name ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.family_segments (family_id,segment_id,is_primary) SELECT fm.id, sg.id, v.pri FROM (VALUES
('agulhas-descartaveis','Avicultura',true),
('agulhas-inox-reutilizaveis','Avicultura',true),
('agulhas-para-aplicador-de-vacina','Avicultura',true),
('seringas-automaticas-de-fluxo-continuo','Avicultura',true),
('seringas-automaticas-duplas','Avicultura',true),
('vacinadoras-com-porta-frasco','Avicultura',true),
('kits-de-reparo-para-seringas-automaticas','Avicultura',true),
('seringas-descartaveis','Avicultura',true),
('equipos-para-aplicacao-e-infusao','Avicultura',true),
('bicos-pulverizadores','Avicultura',true),
('tubulacoes-e-mangueiras','Avicultura',true),
('balancas-suspensas-e-dinamometros-para-aves','Avicultura',true),
('balancas-eletronicas-para-aves','Avicultura',true),
('balancas-para-ovos','Avicultura',true),
('balancas-de-precisao-de-bolso','Avicultura',true),
('termometros','Avicultura',true),
('medidores-e-testes-de-qualidade-da-agua','Avicultura',true),
('testes-de-qualidade-do-ambiente','Avicultura',true),
('equipamentos-para-ovoscopia','Avicultura',true),
('cameras-termograficas','Avicultura',true),
('laminas-para-debicagem','Avicultura',true),
('bebedouros-pendulares-para-aves','Avicultura',true),
('comedouros-para-aves','Avicultura',true),
('niples-para-bebedouro','Avicultura',true),
('armadilhas-para-roedores','Avicultura',true),
('adesivos-e-colas-para-captura','Avicultura',true),
('contadores-manuais-para-aves','Avicultura',true),
('consumiveis-de-assepsia-e-apoio','Avicultura',true),
('conjunto-para-aplicacao-de-tuberculina','Bovinocultura',true),
('seringas-para-insulina','Bovinocultura',true),
('imas-intra-ruminais','Bovinocultura',true)
) AS v(fslug,sname,pri) JOIN public.product_families fm ON fm.slug=v.fslug JOIN public.segments sg ON sg.name=v.sname ON CONFLICT DO NOTHING;
INSERT INTO public.family_applications (family_id,application_id,is_primary) SELECT fm.id, ap.id, v.pri FROM (VALUES
('agulhas-descartaveis','vacinação',true),
('agulhas-descartaveis','aplicação',false),
('agulhas-descartaveis','biossegurança',false),
('agulhas-inox-reutilizaveis','vacinação',true),
('agulhas-inox-reutilizaveis','aplicação',false),
('agulhas-inox-reutilizaveis','reposição',false),
('agulhas-para-aplicador-de-vacina','vacinação',true),
('agulhas-para-aplicador-de-vacina','aplicação',false),
('agulhas-para-aplicador-de-vacina','reposição',false),
('seringas-automaticas-de-fluxo-continuo','vacinação',true),
('seringas-automaticas-de-fluxo-continuo','aplicação',false),
('seringas-automaticas-duplas','vacinação',true),
('seringas-automaticas-duplas','aplicação',false),
('vacinadoras-com-porta-frasco','vacinação',true),
('vacinadoras-com-porta-frasco','aplicação',false),
('kits-de-reparo-para-seringas-automaticas','manutenção',true),
('kits-de-reparo-para-seringas-automaticas','vacinação',false),
('kits-de-reparo-para-seringas-automaticas','reposição',false),
('seringas-descartaveis','aplicação',true),
('seringas-descartaveis','vacinação',false),
('equipos-para-aplicacao-e-infusao','aplicação',true),
('equipos-para-aplicacao-e-infusao','manejo',false),
('bicos-pulverizadores','pulverização',true),
('bicos-pulverizadores','vacinação',false),
('bicos-pulverizadores','biossegurança',false),
('tubulacoes-e-mangueiras','circulação de fluidos',true),
('tubulacoes-e-mangueiras','pulverização',false),
('tubulacoes-e-mangueiras','manutenção',false),
('balancas-suspensas-e-dinamometros-para-aves','pesagem',true),
('balancas-suspensas-e-dinamometros-para-aves','manejo',false),
('balancas-suspensas-e-dinamometros-para-aves','monitoramento',false),
('balancas-eletronicas-para-aves','pesagem',true),
('balancas-eletronicas-para-aves','manejo',false),
('balancas-eletronicas-para-aves','monitoramento',false),
('balancas-para-ovos','pesagem',true),
('balancas-para-ovos','incubação',false),
('balancas-para-ovos','inspeção',false),
('balancas-de-precisao-de-bolso','pesagem',true),
('balancas-de-precisao-de-bolso','medição',false),
('termometros','controle de temperatura',true),
('termometros','medição',false),
('termometros','monitoramento',false),
('termometros','inspeção',false),
('medidores-e-testes-de-qualidade-da-agua','qualidade da água',true),
('medidores-e-testes-de-qualidade-da-agua','medição',false),
('medidores-e-testes-de-qualidade-da-agua','hidratação',false),
('medidores-e-testes-de-qualidade-da-agua','biossegurança',false),
('testes-de-qualidade-do-ambiente','qualidade do ambiente',true),
('testes-de-qualidade-do-ambiente','medição',false),
('testes-de-qualidade-do-ambiente','monitoramento',false),
('equipamentos-para-ovoscopia','ovoscopia',true),
('equipamentos-para-ovoscopia','incubação',false),
('equipamentos-para-ovoscopia','inspeção',false),
('cameras-termograficas','monitoramento',true),
('cameras-termograficas','controle de temperatura',false),
('cameras-termograficas','inspeção',false),
('laminas-para-debicagem','debicagem',true),
('laminas-para-debicagem','reposição',false),
('laminas-para-debicagem','manutenção',false),
('bebedouros-pendulares-para-aves','hidratação',true),
('bebedouros-pendulares-para-aves','manejo',false),
('bebedouros-pendulares-para-aves','alimentação',false),
('comedouros-para-aves','alimentação',true),
('comedouros-para-aves','manejo',false),
('niples-para-bebedouro','hidratação',true),
('niples-para-bebedouro','reposição',false),
('niples-para-bebedouro','manutenção',false),
('armadilhas-para-roedores','controle de pragas',true),
('armadilhas-para-roedores','biossegurança',false),
('adesivos-e-colas-para-captura','controle de pragas',true),
('adesivos-e-colas-para-captura','biossegurança',false),
('contadores-manuais-para-aves','manejo',true),
('contadores-manuais-para-aves','monitoramento',false),
('consumiveis-de-assepsia-e-apoio','biossegurança',true),
('consumiveis-de-assepsia-e-apoio','manejo',false),
('consumiveis-de-assepsia-e-apoio','aplicação',false),
('conjunto-para-aplicacao-de-tuberculina','aplicação',true),
('conjunto-para-aplicacao-de-tuberculina','vacinação',false),
('conjunto-para-aplicacao-de-tuberculina','manejo',false),
('seringas-para-insulina','aplicação',true),
('seringas-para-insulina','manejo',false),
('imas-intra-ruminais','manejo',true),
('imas-intra-ruminais','biossegurança',false)
) AS v(fslug,aname,pri) JOIN public.product_families fm ON fm.slug=v.fslug JOIN public.applications ap ON ap.name=v.aname ON CONFLICT DO NOTHING;
INSERT INTO public.family_solutions (family_id,solution_id) SELECT fm.id, so.id FROM (VALUES
('agulhas-descartaveis','Soluções para vacinação'),
('agulhas-inox-reutilizaveis','Soluções para vacinação'),
('agulhas-para-aplicador-de-vacina','Soluções para vacinação'),
('seringas-automaticas-de-fluxo-continuo','Soluções para vacinação'),
('seringas-automaticas-duplas','Soluções para vacinação'),
('vacinadoras-com-porta-frasco','Soluções para vacinação'),
('kits-de-reparo-para-seringas-automaticas','Soluções para vacinação'),
('seringas-descartaveis','Soluções para vacinação'),
('equipos-para-aplicacao-e-infusao','Soluções para vacinação'),
('bicos-pulverizadores','Soluções para pulverização'),
('tubulacoes-e-mangueiras','Soluções para pulverização'),
('balancas-suspensas-e-dinamometros-para-aves','Soluções para pesagem, medição e controle'),
('balancas-eletronicas-para-aves','Soluções para pesagem, medição e controle'),
('balancas-para-ovos','Soluções para pesagem, medição e controle'),
('balancas-de-precisao-de-bolso','Soluções para pesagem, medição e controle'),
('termometros','Soluções para pesagem, medição e controle'),
('medidores-e-testes-de-qualidade-da-agua','Soluções para pesagem, medição e controle'),
('testes-de-qualidade-do-ambiente','Soluções para pesagem, medição e controle'),
('equipamentos-para-ovoscopia','Soluções para pesagem, medição e controle'),
('cameras-termograficas','Soluções para pesagem, medição e controle'),
('laminas-para-debicagem','Reposição e manutenção'),
('bebedouros-pendulares-para-aves','Manejo e biossegurança'),
('comedouros-para-aves','Manejo e biossegurança'),
('niples-para-bebedouro','Manejo e biossegurança'),
('armadilhas-para-roedores','Manejo e biossegurança'),
('adesivos-e-colas-para-captura','Manejo e biossegurança'),
('contadores-manuais-para-aves','Manejo e biossegurança'),
('consumiveis-de-assepsia-e-apoio','Manejo e biossegurança'),
('conjunto-para-aplicacao-de-tuberculina','Linhas complementares'),
('seringas-para-insulina','Linhas complementares'),
('imas-intra-ruminais','Linhas complementares')
) AS v(fslug,sname) JOIN public.product_families fm ON fm.slug=v.fslug JOIN public.solutions so ON so.name=v.sname ON CONFLICT DO NOTHING;
CREATE UNIQUE INDEX IF NOT EXISTS products_public_sku_active_uidx ON public.products (upper(public_sku)) WHERE deleted_at IS NULL;